In [16]:
import pandas as pd
import numpy as np

In [17]:
import seaborn as sns
df = sns.load_dataset('titanic')

In [18]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [19]:
print( df.shape )

(891, 15)

In [20]:
df_copy1 = df.copy()

In [21]:
df_encoded = pd.get_dummies( df_copy1, columns=["embarked"] )
#one hot encoding has been added for the "embarked" columns
#"embarked" feature has been removed

In [22]:
df_encoded.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone,embarked_C,embarked_Q,embarked_S
0,0,3,male,22.0,1,0,7.2500,Third,man,True,NaN,Southampton,no,False,False,False,True
1,1,1,female,38.0,1,0,71.2833,First,woman,False,C,Cherbourg,yes,False,True,False,False
2,1,3,female,26.0,0,0,7.9250,Third,woman,False,NaN,Southampton,yes,True,False,False,True
3,1,1,female,35.0,1,0,53.1000,First,woman,False,C,Southampton,yes,False,False,False,True
4,0,3,male,35.0,0,0,8.0500,Third,man,True,NaN,Southampton,no,True,False,False,True

In [23]:
print( df_encoded.shape )

(891, 17)

In [24]:
df_copy2 = df.copy()

In [25]:
df_encoded_2 = pd.get_dummies( df_copy2, columns=["embarked"], drop_first = True )
#one hot encoding has been added for the "embarked" columns
#"embarked" feature has been removed
#"embarked_C" is not a feature in this dataframe

In [26]:
df_encoded_2.head()

,survived,pclass,sex,age,sibsp,parch,fare,class,who,adult_male,deck,embark_town,alive,alone,embarked_Q,embarked_S
0,0,3,male,22.0,1,0,7.2500,Third,man,True,NaN,Southampton,no,False,False,True
1,1,1,female,38.0,1,0,71.2833,First,woman,False,C,Cherbourg,yes,False,False,False
2,1,3,female,26.0,0,0,7.9250,Third,woman,False,NaN,Southampton,yes,True,False,True
3,1,1,female,35.0,1,0,53.1000,First,woman,False,C,Southampton,yes,False,False,True
4,0,3,male,35.0,0,0,8.0500,Third,man,True,NaN,Southampton,no,True,False,True

In [27]:
print( df_encoded_2.shape )

(891, 16)

In [28]:
df_copy3 = df.copy()

In [29]:
df_who = pd.get_dummies( df_copy3, columns=["who"] )

In [30]:
df_who.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone,who_child,who_man,who_woman
0,0,3,male,22.0,1,0,7.2500,S,Third,True,NaN,Southampton,no,False,False,True,False
1,1,1,female,38.0,1,0,71.2833,C,First,False,C,Cherbourg,yes,False,False,False,True
2,1,3,female,26.0,0,0,7.9250,S,Third,False,NaN,Southampton,yes,True,False,False,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,C,Southampton,yes,False,False,False,True
4,0,3,male,35.0,0,0,8.0500,S,Third,True,NaN,Southampton,no,True,False,True,False

In [31]:
print( df_who.shape )

(891, 17)

In [32]:
df_copy4 = df.copy()

In [33]:
df_class = pd.get_dummies( df_copy4, columns=["class"] )

In [34]:
df_class.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,who,adult_male,deck,embark_town,alive,alone,class_First,class_Second,class_Third
0,0,3,male,22.0,1,0,7.2500,S,man,True,NaN,Southampton,no,False,False,False,True
1,1,1,female,38.0,1,0,71.2833,C,woman,False,C,Cherbourg,yes,False,True,False,False
2,1,3,female,26.0,0,0,7.9250,S,woman,False,NaN,Southampton,yes,True,False,False,True
3,1,1,female,35.0,1,0,53.1000,S,woman,False,C,Southampton,yes,False,True,False,False
4,0,3,male,35.0,0,0,8.0500,S,man,True,NaN,Southampton,no,True,False,False,True

In [35]:
print( df_class.shape )

(891, 17)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df_copy5 = df.copy()

In [ ]:
encoder = OrdinalEncoder( categories=[ ["Third", "Second", "First"] ]  )

In [ ]:
df_copy5[ "class_encoded" ] = encoder.fit_transform( df[ ["class"] ] )

In [ ]:
df_copy5.head()

In [ ]:
print( df_copy5.shape )

(891, 17)