

1. Load the dataset
2. Explore the dataset
3. Handle missing values ( if any )
4. Check duplicates
5. Calculate mean, median, std
6. Detect Outliers( IQR, LL, UL )
7. Normalize numerical features
8. Standardize numerical features
9. Save the clean dataset

1. Remove unnecessary features
2. Which features are categorical and which are numerical ?
3. Update a value of dataset by selecting a row or column

In [207]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the dataset

In [240]:
import seaborn as sns
df = sns.load_dataset('titanic')

In [241]:
df_backup = df.copy()

# Explore the dataset

In [242]:
df.head()
#df = pd.DataFrame( df ) - not required yet

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [243]:
print(df.columns)

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [244]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [245]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [246]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [247]:
col_corr = {  }
for col in df.columns:
  col_corr[col] = len(df[col])

print(col_corr)

{'survived': 891, 'pclass': 891, 'sex': 891, 'age': 891, 'sibsp': 891, 'parch': 891, 'fare': 891, 'embarked': 891, 'class': 891, 'who': 891, 'adult_male': 891, 'deck': 891, 'embark_town': 891, 'alive': 891, 'alone': 891}

In [248]:
max_samples = 0
for key in col_corr.keys():
  if( col_corr[key] > max_samples ) :
    max_samples = col_corr[key]
    #max_col = key

print(max_samples)

891

# Q1) Which features are categorical and which are numerical ?

Ans :

*   Categorical


1. sex
2. embarked
3. who
4. deck
5. embark_town
6. alive


*   Numerical


1. survived
2. pclass
3. age
4. sibsp
5. parch
6. fare
7. class
8. adult_male
9. alone

# Q2) Remove unnecessary features

1. since "sex" and "who" columns give information about the same data,
either of them can be removed.

In [249]:
df = df.drop("who", axis=1)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True,NaN,Southampton,no,True

2. since "survived" and "alive" columns give information about the same data,
either of them can be removed;
removing "alive" is more preferrable since "survived" is already present in one hot encoding format

In [250]:
df = df.drop("alive", axis=1)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,True,NaN,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,First,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,Third,False,NaN,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True,NaN,Southampton,True

In [251]:
df = df.drop("adult_male", axis=1)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,deck,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,NaN,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,First,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,Third,NaN,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,First,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,Third,NaN,Southampton,True

In [252]:
df = df.drop("deck", axis=1)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,First,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,Third,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,First,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,Third,Southampton,True

In [220]:
#df = df.drop("embark_town", axis=1)
#df.head()

3. since we cannot calculate mean or other operations for string or categorical data ( columns "embark_town" and "deck" ) , we will replace the null values with a substitute string; say 'U'

In [221]:
#df["embark_town"].replace( np.nan, "U", inplace=True )
#df["deck"].replace( np.nan, "U", inplace=True )

#df["deck"].fillna( "U", inplace=True )
#df.head()

In [222]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   deck         203 non-null    category
 10  embark_town  889 non-null    object
 11  alone        891 non-null    bool
dtypes: bool(1), category(2), float64(2), int64(4), object(3)
memory usage: 65.9+ KB

replacing null values in "age" column with mean/avg value

In [253]:
df["age"] = df["age"].fillna( df["age"].mean() )

In [254]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   embark_town  889 non-null    object
 10  alone        891 non-null    bool
dtypes: bool(1), category(1), float64(2), int64(4), object(3)
memory usage: 64.6+ KB

Ordinal Encoding for "class" column/attribute

In [255]:
from sklearn.preprocessing import OrdinalEncoder

In [256]:
encoder = OrdinalEncoder( categories=[ ["Third", "Second", "First"] ]  )

In [257]:
df_class = df[ "class" ]

In [258]:
df["class"] = encoder.fit_transform( df_class.values.reshape(-1,1) )

Scaling the numerical features using StandardScaler

In [260]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    float64
 9   embark_town  889 non-null    object
 10  alone        891 non-null    bool
dtypes: bool(1), float64(3), int64(4), object(3)
memory usage: 70.6+ KB

In [261]:
df_without_scaling = df.copy()

In [262]:
from sklearn.preprocessing import StandardScaler

In [263]:
scaler_instance = StandardScaler()

In [266]:
cols_to_be_scaled = []

for col in df.columns :
  if(  ( (df[col].dtype == int) or (df[col].dtype == float ) and (df[col].max() > 1) ) ) :
    cols_to_be_scaled.append( col )

print(cols_to_be_scaled)

['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare', 'class']

In [271]:
df.head()

          0         1         2         3         4         5         6
0 -0.789272  0.827377 -0.592481  0.432793 -0.473674 -0.502445 -0.827377
1  1.266990 -1.566107  0.638789  0.432793 -0.473674  0.786845  1.566107
2  1.266990  0.827377 -0.284663 -0.474545 -0.473674 -0.488854 -0.827377
3  1.266990 -1.566107  0.407926  0.432793 -0.473674  0.420730  1.566107
4 -0.789272  0.827377  0.407926 -0.474545 -0.473674 -0.486337 -0.827377

In [270]:
#df = scaler_instance.fit_transform( df[cols_to_be_scaled] )
#df = pd.DataFrame( df )

for col in cols_to_be_scaled :
  df[col] = scaler_instance.fit_transform( df[col].values.reshape(-1,1) )

KeyError: 'survived'

In [268]:
df.head()

          0         1         2         3         4         5         6
0 -0.789272  0.827377 -0.592481  0.432793 -0.473674 -0.502445 -0.827377
1  1.266990 -1.566107  0.638789  0.432793 -0.473674  0.786845  1.566107
2  1.266990  0.827377 -0.284663 -0.474545 -0.473674 -0.488854 -0.827377
3  1.266990 -1.566107  0.407926  0.432793 -0.473674  0.420730  1.566107
4 -0.789272  0.827377  0.407926 -0.474545 -0.473674 -0.486337 -0.827377

One Hot Encoding for categorical data

In [237]:
df = pd.get_dummies( df, columns=["sex"] )
df.head()

KeyError: "None of [Index(['sex'], dtype='object')] are in the [columns]"

In [ ]:
df = pd.get_dummies( df, columns=["embark_town"] )
df.head()

In [ ]:
df = pd.get_dummies( df, columns=["embarked"] )
df.head()

In [ ]:
df = pd.get_dummies( df, columns=["deck"] )
df.head()

In [ ]:
#df[ "alone" ] = df[ "alone" ].astype( int )
#df.head()

In [ ]:
for col in df.columns :
  if( df[col].dtype != int ) :
    df[col] = df[col].astype(int)

df.head()

In [ ]:
max_list = []
min_list = []

for col in df.columns :
  max_list.append( df[col].max() )
  min_list.append( df[col].min() )

In [ ]:
plt.plot( np.arange( len(max_list)), max_list )
plt.show()

In [ ]:
plt.plot( np.arange( len(min_list)), min_list )
plt.show()

In [ ]:
#df = scaler_instance.fit_transform(df)
#df = pd.DataFrame( df, columns=df_without_scaling.columns )