In [2]:
import pandas as pd
import numpy as np

In [3]:
!wget https://raw.githubusercontent.com/durveshcollegeid/sem5_ML/refs/heads/main/aug28/adult/adult.data

--2026-09-08 04:24:26--  https://raw.githubusercontent.com/durveshcollegeid/sem5_ML/refs/heads/main/aug28/adult/adult.data
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3974305 (3.8M) [text/plain]
Saving to: ‘adult.data’

adult.data          100%[===================>]   3.79M  --.-KB/s    in 0.05s

2026-09-08 04:24:27 (76.1 MB/s) - ‘adult.data’ saved [3974305/3974305]

In [4]:
path = "/content/adult.data"

In [17]:
df = pd.read_csv( path )
df_backup = pd.read_csv( path )
df_backup_copy = pd.read_csv( path )

In [18]:
col_list = [ "age", "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "income" ]

In [19]:
df.columns = col_list
df_backup.columns = col_list
df_backup_copy.columns = col_list

nunique(), unique(), count()

In [43]:
df_new = df_backup
#df_new = pd.DataFrame(columns = col_list)

In [52]:
#for col in col_list :
#  df_new["new"+col] = df_new[col].replace( "?", np.nan )
#  df_new.drop(col)

In [51]:
df_new.nunique( axis=0 ) #number of unique values per column

age                  73
workclass             9
fnlwgt            21647
education            16
education-num        16
marital-status        7
occupation           15
relationship          6
race                  5
sex                   2
capital-gain        119
capital-loss         92
hours-per-week       94
native-country       42
income                2
dtype: int64

In [50]:
df_new.nunique( axis=1 ) #number of unique values per row

0        13
1        14
2        14
3        14
4        14
         ..
32555    14
32556    13
32557    14
32558    14
32559    15
Length: 32560, dtype: int64

In [49]:
df_new.nunique( axis=0, dropna=True ) #number of not-null unique values per column

age                  73
workclass             9
fnlwgt            21647
education            16
education-num        16
marital-status        7
occupation           15
relationship          6
race                  5
sex                   2
capital-gain        119
capital-loss         92
hours-per-week       94
native-country       42
income                2
dtype: int64

In [48]:
df_new.nunique( axis=1, dropna=True ) #number of not-null unique values per row

0        13
1        14
2        14
3        14
4        14
         ..
32555    14
32556    13
32557    14
32558    14
32559    15
Length: 32560, dtype: int64

In [47]:
df_new.count( axis=0) #number of not-null unique values per column

age               32560
workclass         32560
fnlwgt            32560
education         32560
education-num     32560
marital-status    32560
occupation        32560
relationship      32560
race              32560
sex               32560
capital-gain      32560
capital-loss      32560
hours-per-week    32560
native-country    32560
income            32560
dtype: int64

In [46]:
df_new.count( axis=1) #number of not-null unique values per column

0        15
1        15
2        15
3        15
4        15
         ..
32555    15
32556    15
32557    15
32558    15
32559    15
Length: 32560, dtype: int64

In [53]:
#df_new["age"].unique()

array([50, 38, 53, 28, 37, 49, 52, 31, 42, 30, 23, 32, 40, 34, 25, 43, 54,
       35, 59, 56, 19, 39, 20, 45, 22, 48, 21, 24, 57, 44, 41, 29, 18, 47,
       46, 36, 79, 27, 67, 33, 76, 17, 55, 61, 70, 64, 71, 68, 66, 51, 58,
       26, 60, 90, 75, 65, 77, 62, 63, 80, 72, 74, 69, 73, 81, 78, 88, 82,
       83, 84, 85, 86, 87])

Defining manual bins for pd.cut()

In [57]:
df_new["new_age"] = pd.cut( df_new["age"], bins=[0,11,18,45,60], labels=["Young", "Minor", "Adult", "Old"] )

In [58]:
df_new.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income,new_age
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,Old
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,Adult
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,Old
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,Adult
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K,Adult

Allowing automatic bins for pd.cut()

In [60]:
df_new["auto_age"] = pd.cut( df_new["age"], bins=4, labels=["Young", "Minor", "Adult", "Old"] )

In [61]:
df_new.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income,new_age,auto_age
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,Old,Minor
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,Adult,Minor
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,Old,Minor
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,Adult,Young
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K,Adult,Minor

Count comparison

In [ ]:
df_new["auto_age"].nunique()

4

In [ ]:
labels=["Young", "Minor", "Adult", "Old"]

print( "automatic cut" )
for x in labels :
  print( "count of " +x + " = " + str(int(df_new[ df_new["auto_age"] == x ]["auto_age"].count())) )

automatic cut
count of Young = 14925
count of Minor = 12712
count of Adult = 4455
count of Old = 468

In [ ]:
print( "manual cut" )
for x in labels :
  print( "count of " +x + " = " + str(int(df_new[ df_new["new_age"] == x ]["new_age"].count())) )

manual cut
count of Young = 0
count of Minor = 945
count of Adult = 21988
count of Old = 7295