# import pandas and required data

In [1]:
import pandas as pd
import numpy as np

In [3]:
!wget "https://raw.githubusercontent.com/durveshcollegeid/sem5_ML/refs/heads/main/train_28jul%20(1).csv"

--2026-09-09 04:20:27--  https://raw.githubusercontent.com/durveshcollegeid/sem5_ML/refs/heads/main/train_28jul%20(1).csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 460676 (450K) [text/plain]
Saving to: ‘train_28jul (1).csv’

train_28jul (1).csv 100%[===================>] 449.88K  --.-KB/s    in 0.1s

2026-09-09 04:20:27 (3.52 MB/s) - ‘train_28jul (1).csv’ saved [460676/460676]

In [4]:
path = "/content/train_28jul (1).csv"

# create a pandas DataFrame from the csv file

In [6]:
df = pd.read_csv( path )
df_copy = pd.read_csv( path )

In [7]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [8]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

# use groupby for "Neighborhood" column

In [19]:
df_grouped = df.groupby('Neighborhood')

In [24]:
df_grouped = pd.DataFrame( df_grouped )
df_grouped.columns = ['Neighborhood', 'data']
df_grouped.head()

  Neighborhood                                               data
0      Blmngtn          Id  MSSubClass MSZoning  LotFrontage  ...
1      Blueste        Id  MSSubClass MSZoning  LotFrontage  Lo...
2       BrDale          Id  MSSubClass MSZoning  LotFrontage  ...
3      BrkSide          Id  MSSubClass MSZoning  LotFrontage  ...
4      ClearCr          Id  MSSubClass MSZoning  LotFrontage  ...

# Relation between unique values in df and shape of df_grouped

In [22]:
df['Neighborhood'].unique(), len(df['Neighborhood'].unique())

(array(['CollgCr', 'Veenker', 'Crawfor', 'NoRidge', 'Mitchel', 'Somerst',
        'NWAmes', 'OldTown', 'BrkSide', 'Sawyer', 'NridgHt', 'NAmes',
        'SawyerW', 'IDOTRR', 'MeadowV', 'Edwards', 'Timber', 'Gilbert',
        'StoneBr', 'ClearCr', 'NPkVill', 'Blmngtn', 'BrDale', 'SWISU',
        'Blueste'], dtype=object),
 25)

In [25]:
print( df.shape, df_grouped.shape )

(1460, 81) (25, 2)

# Aggregate function on grouped data

In [26]:
df_grouped_original = df.groupby('Neighborhood')

In [28]:
df_grouped_original['SalePrice'].mean()

Neighborhood
Blmngtn    194870.882353
Blueste    137500.000000
BrDale     104493.750000
BrkSide    124834.051724
ClearCr    212565.428571
CollgCr    197965.773333
Crawfor    210624.725490
Edwards    128219.700000
Gilbert    192854.506329
IDOTRR     100123.783784
MeadowV     98576.470588
Mitchel    156270.122449
NAmes      145847.080000
NPkVill    142694.444444
NWAmes     189050.068493
NoRidge    335295.317073
NridgHt    316270.623377
OldTown    128225.300885
SWISU      142591.360000
Sawyer     136793.135135
SawyerW    186555.796610
Somerst    225379.837209
StoneBr    310499.000000
Timber     242247.447368
Veenker    238772.727273
Name: SalePrice, dtype: float64

In [29]:
df_grouped_original['SalePrice'].max()

Neighborhood
Blmngtn    264561
Blueste    151000
BrDale     125000
BrkSide    223500
ClearCr    328000
CollgCr    424870
Crawfor    392500
Edwards    320000
Gilbert    377500
IDOTRR     169500
MeadowV    151400
Mitchel    271000
NAmes      345000
NPkVill    155000
NWAmes     299800
NoRidge    755000
NridgHt    611657
OldTown    475000
SWISU      200000
Sawyer     190000
SawyerW    320000
Somerst    423000
StoneBr    556581
Timber     378500
Veenker    385000
Name: SalePrice, dtype: int64

# Grouping on multiple feature columns

In [32]:
df_multi_grouped = df.groupby(['Neighborhood', 'Street'] )

In [34]:
df_multi_grouped['SalePrice'].mean()

Neighborhood  Street
Blmngtn       Pave      194870.882353
Blueste       Pave      137500.000000
BrDale        Pave      104493.750000
BrkSide       Pave      124834.051724
ClearCr       Pave      212565.428571
CollgCr       Pave      197965.773333
Crawfor       Pave      210624.725490
Edwards       Grvl      118500.000000
              Pave      128317.878788
Gilbert       Pave      192854.506329
IDOTRR        Grvl       82331.000000
              Pave      101693.735294
MeadowV       Pave       98576.470588
Mitchel       Pave      156270.122449
NAmes         Pave      145847.080000
NPkVill       Pave      142694.444444
NWAmes        Pave      189050.068493
NoRidge       Pave      335295.317073
NridgHt       Pave      316270.623377
OldTown       Pave      128225.300885
SWISU         Pave      142591.360000
Sawyer        Pave      136793.135135
SawyerW       Pave      186555.796610
Somerst       Pave      225379.837209
StoneBr       Pave      310499.000000
Timber        Grvl      207825.000000
              Pave      244159.805556
Veenker       Pave      238772.727273
Name: SalePrice, dtype: float64

In [35]:
df_multi_grouped['SalePrice'].max()

Neighborhood  Street
Blmngtn       Pave      264561
Blueste       Pave      151000
BrDale        Pave      125000
BrkSide       Pave      223500
ClearCr       Pave      328000
CollgCr       Pave      424870
Crawfor       Pave      392500
Edwards       Grvl      118500
              Pave      320000
Gilbert       Pave      377500
IDOTRR        Grvl      110000
              Pave      169500
MeadowV       Pave      151400
Mitchel       Pave      271000
NAmes         Pave      345000
NPkVill       Pave      155000
NWAmes        Pave      299800
NoRidge       Pave      755000
NridgHt       Pave      611657
OldTown       Pave      475000
SWISU         Pave      200000
Sawyer        Pave      190000
SawyerW       Pave      320000
Somerst       Pave      423000
StoneBr       Pave      556581
Timber        Grvl      228950
              Pave      378500
Veenker       Pave      385000
Name: SalePrice, dtype: int64

In [36]:
df_multi_grouped['SalePrice'].describe()

                     count           mean            std       min        25%  \
Neighborhood Street
Blmngtn      Pave     17.0  194870.882353   30393.229219  159895.0  174000.00
Blueste      Pave      2.0  137500.000000   19091.883092  124000.0  130750.00
BrDale       Pave     16.0  104493.750000   14330.176493   83000.0   91000.00
BrkSide      Pave     58.0  124834.051724   40348.689270   39300.0  100500.00
ClearCr      Pave     28.0  212565.428571   50231.538993  130000.0  183750.00
CollgCr      Pave    150.0  197965.773333   51403.666438  110000.0  152958.75
Crawfor      Pave     51.0  210624.725490   68866.395472   90350.0  159250.00
Edwards      Grvl      1.0  118500.000000            NaN  118500.0  118500.00
             Pave     99.0  128317.878788   43417.296734   58500.0  101000.00
Gilbert      Pave     79.0  192854.506329   35986.779085  141000.0  174000.00
IDOTRR       Grvl      3.0   82331.000000   27028.090628   55993.0   68496.50
             Pave     34.0  101693.735294   33759.212329   34900.0   84625.00
MeadowV      Pave     17.0   98576.470588   23491.049610   75000.0   83500.00
Mitchel      Pave     49.0  156270.122449   36486.625334   84500.0  131000.00
NAmes        Pave    225.0  145847.080000   33075.345450   87500.0  127500.00
NPkVill      Pave      9.0  142694.444444    9377.314529  127500.0  140000.00
NWAmes       Pave     73.0  189050.068493   37172.218106   82500.0  165150.00
NoRidge      Pave     41.0  335295.317073  121412.658640  190000.0  265000.00
NridgHt      Pave     77.0  316270.623377   96392.544954  154000.0  253293.00
OldTown      Pave    113.0  128225.300885   52650.583185   37900.0  105900.00
SWISU        Pave     25.0  142591.360000   32622.917679   60000.0  128000.00
Sawyer       Pave     74.0  136793.135135   22345.129157   62383.0  127250.00
SawyerW      Pave     59.0  186555.796610   55651.997820   76000.0  145500.00
Somerst      Pave     86.0  225379.837209   56177.555888  144152.0  177975.00
StoneBr      Pave     25.0  310499.000000  112969.676640  170000.0  213500.00
Timber       Grvl      2.0  207825.000000   29875.261505  186700.0  197262.50
             Pave     36.0  244159.805556   65941.417357  137500.0  186625.00
Veenker      Pave     11.0  238772.727273   72369.317959  162500.0  184250.00

                          50%        75%       max
Neighborhood Street
Blmngtn      Pave    191000.0  213490.00  264561.0
Blueste      Pave    137500.0  144250.00  151000.0
BrDale       Pave    106000.0  118000.00  125000.0
BrkSide      Pave    124300.0  141175.00  223500.0
ClearCr      Pave    200250.0  242225.00  328000.0
CollgCr      Pave    197200.0  225725.00  424870.0
Crawfor      Pave    200624.0  239000.00  392500.0
Edwards      Grvl    118500.0  118500.00  118500.0
             Pave    123500.0  145450.00  320000.0
Gilbert      Pave    181000.0  197200.00  377500.0
IDOTRR       Grvl     81000.0   95500.00  110000.0
             Pave    104750.0  124250.00  169500.0
MeadowV      Pave     88000.0  115000.00  151400.0
Mitchel      Pave    153500.0  171000.00  271000.0
NAmes        Pave    140000.0  158000.00  345000.0
NPkVill      Pave    146000.0  148500.00  155000.0
NWAmes       Pave    182900.0  205000.00  299800.0
NoRidge      Pave    301500.0  341000.00  755000.0
NridgHt      Pave    315000.0  374000.00  611657.0
OldTown      Pave    119000.0  140000.00  475000.0
SWISU        Pave    139500.0  160000.00  200000.0
Sawyer       Pave    135000.0  149462.50  190000.0
SawyerW      Pave    179900.0  222500.00  320000.0
Somerst      Pave    225500.0  252919.50  423000.0
StoneBr      Pave    278000.0  377426.00  556581.0
Timber       Grvl    207825.0  218387.50  228950.0
             Pave    233500.0  288519.25  378500.0
Veenker      Pave    218000.0  282000.00  385000.0

# Aggregation dictionary on multiple data columns using .agg()

In [38]:
df_multidata = df.groupby( "Neighborhood" ).agg(
    {
        "SalePrice": "mean",
        'GarageCars': "max"
    }
)

In [39]:
df_multidata

                  SalePrice  GarageCars
Neighborhood
Blmngtn       194870.882353           3
Blueste       137500.000000           2
BrDale        104493.750000           2
BrkSide       124834.051724           2
ClearCr       212565.428571           2
CollgCr       197965.773333           3
Crawfor       210624.725490           3
Edwards       128219.700000           3
Gilbert       192854.506329           3
IDOTRR        100123.783784           3
MeadowV        98576.470588           2
Mitchel       156270.122449           4
NAmes         145847.080000           4
NPkVill       142694.444444           2
NWAmes        189050.068493           3
NoRidge       335295.317073           3
NridgHt       316270.623377           3
OldTown       128225.300885           4
SWISU         142591.360000           2
Sawyer        136793.135135           2
SawyerW       186555.796610           3
Somerst       225379.837209           3
StoneBr       310499.000000           3
Timber        242247.447368           3
Veenker       238772.727273           3

In [40]:
df_multidata.describe()

           SalePrice  GarageCars
count      25.000000   25.000000
mean   183964.853300    2.800000
std     66725.196972    0.645497
min     98576.470588    2.000000
25%    136793.135135    2.000000
50%    186555.796610    3.000000
75%    212565.428571    3.000000
max    335295.317073    4.000000

# transform the dataframe

In [47]:
df_copy = pd.read_csv(path)

In [48]:
df_copy["mean_saleprice_wrt_neighbourhood"] = df.groupby("Neighborhood")["SalePrice"].transform("mean")

In [49]:
df_copy.head(20)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,mean_saleprice_wrt_neighbourhood
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,197965.773333
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,238772.727273
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,9,2008,WD,Normal,223500,197965.773333
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000,210624.725490
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,12,2008,WD,Normal,250000,335295.317073
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000,156270.122449
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,8,2007,WD,Normal,307000,225379.837209
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,Shed,350,11,2009,WD,Normal,200000,189050.068493
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900,128225.300885
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,1,2008,WD,Normal,118000,124834.051724
10,11,20,RL,70.0,11200,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2008,WD,Normal,129500,136793.135135
11,12,60,RL,85.0,11924,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,7,2006,New,Partial,345000,316270.623377
12,13,20,RL,NaN,12968,Pave,NaN,IR2,Lvl,AllPub,...,NaN,NaN,NaN,0,9,2008,WD,Normal,144000,136793.135135
13,14,20,RL,91.0,10652,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,8,2007,New,Partial,279500,197965.773333
14,15,20,RL,NaN,10920,Pave,NaN,IR1,Lvl,AllPub,...,NaN,GdWo,NaN,0,5,2008,WD,Normal,157000,145847.080000
15,16,45,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,NaN,GdPrv,NaN,0,7,2007,WD,Normal,132000,124834.051724
16,17,20,RL,NaN,11241,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,Shed,700,3,2010,WD,Normal,149000,145847.080000
17,18,90,RL,72.0,10791,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,Shed,500,10,2006,WD,Normal,90000,136793.135135
18,19,20,RL,66.0,13695,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,6,2008,WD,Normal,159000,186555.796610
19,20,20,RL,70.0,7560,Pave,NaN,Reg,Lvl,AllPub,...,NaN,MnPrv,NaN,0,5,2009,COD,Abnorml,139000,145847.080000